------------------ Simbolo inicial ------------------
<programa>
-------------------- Terminales --------------------

Palabras reservadas

Variables, funciones y tipos de datos
    "val"       
    "int"          
    "float"       
    "bool"         
    "char"         
    "string"       
    "void"         
    "true"         
    "false"        
Estructuras condicionales
    "if"           
    "elif"         
    "else"         
Ciclos y control de funciones
    "while"        
    "for"          
    "return"       
    "break"  
    "print"      
    "principal"  
Entrada y salida de datos
    "read"       
    "write"   
Operadores aritmeticos
    Binarios
        "+"           
        "-"           
        "*"           
        "/"         
        "//"         
        "mod"        
        "pot"        
    Unarios
        "-"          
        "++"         
        "--"          
Operadores relacionales
    "<"            
    ">"            
    "<="           
    ">="          
    "=="         
    "!="           
Operadores logicos
    "λ"            (and)
    "θ"            (or)
    "Σ"            (not)
Delimitadores y simbolos literales
    Bloques
        "¿:"           (Abre )
        ":?"           (Cierra)
    Parentesis
        "є:"           (Abre )
        ":э"           (Cierra )
    Indices de arreglos
        "ʃ:"           (Inicia )
        ":ʅ"           (Cierra )
    Otros
        "»"            (Final de expresion)
        "Ͱ"            (Asignacion)
        ","            (Separador para parametros de funcion)
Comentarios
    "|"            (Comentario de linea)
    "¡"            (Abre comentario multilinea)
    "!"            (Cierra comentario multilinea)

Digitos
    "0" "1" "2" "3" "4" "5" "6" "7" "8" "9"
Letras
    "a" "b" "c" "d" "e" "f" "g" "h" "i" "j" "k" "l" "m" "n" "o" "p" "q" "r" "s" "t" "u" "v" "w" "x" "y" "z" "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N" "O" "P" "Q" "R" "S" "T" "U" "V" "W" "X" "Y" "Z"

------------------- No Terminales -------------------

Caracteres y texto
    <letra>
    <digito>
    <digito_no_cero>
    <cero>
    <lista_digitos>
    <simbolo>
    <espacio>
    <caracter>
    <texto>
    <comillaDoble>
    <comillaSimple>
    <guionBajo>

Literales y tipos
    <entero>
    <lista_digitos_no_cero_final>
    <flotante>
    <true>
    <false>
    <bool>
    <cadena_texto>
    <caracter_literal>
    <valor_numerico>
    <valor>
    <tipo>
    <tipoInt>
    <tipoFloat>
    <tipoBool>
    <tipoChar>
    <tipoString>
    <tipoVoid>
    <identificador>
    <resto_id>

Delimitadores
    <abrir_bloque>
    <cerrar_bloque>
    <abrir_parentesis>
    <cerrar_parentesis>
    <abrir_corcheteCuadrados>
    <cerrar_corcheteCuadrados>
    <coma>
    <fin_sentencia>
    <asignacion>
    <incremento>
    <decremento>

Palabras reservadas y operadores
    <palabraVal>
    <palabraBreak>
    <palabraReturn>
    <palabraPrint>
    <palabraPrincipal>
    <palabraIf>
    <palabraElif>
    <palabraElse>
    <palabraWhile>
    <palabraFor>
    <operadorPotencia>
    <modulo>
    <not>
    <leer>
    <escribir>
    <vacio>

Operadores
    <simboloSuma>
    <simboloResta>
    <simboloMultiplicacion>
    <simboloDivision>
    <simboloDivisionEntera>
    <simboloMenor>
    <simboloMayor>
    <simboloMenorIgual>
    <simboloMayorIgual>
    <simboloIgual>
    <simboloDiferente>
    <simboloAnd>
    <simboloOr>

Variables
    <variable>
    <def_variable>
    <asignacion_variable>
    <lista_globales>

Entrada y salida
    <lectura>
    <escritura>
    <impresion>
    <lista_valores>
    <valor_escritura>

Arreglos
    <indice>
    <arreglo>
    <acceso_arreglo>
    <declaracion_arreglo>
    <creacion_arreglo>
    <arreglo_con_tamano>
    <arreglo_con_tamano_valores>
    <arreglo_sin_tamano_valores>
    <lista_arreglo>
    <inicio_lista_arreglo>
    <continuacion_lista_arreglo>
    <modificacion_arreglo>
    <tipo_arreglo>

Operaciones aritmeticas
    <valor_aritmetico>
    <expresion_potencia>
    <exponente>
    <expresion_unaria>
    <expresion_suma>
    <expresion_multiplicacion>
    <expresion_aritmetica>
    <operador_suma>
    <operador_multiplicacion>
    <operacion_incremento>

Operaciones relacionales
    <operadorRelacional>
    <operando_relacional>
    <operacion_relacional>

Expresiones logicas
    <condicion_basica>
    <condiciones_and>
    <condiciones_or>
    <condiciones_logicas>
    <negacion>
    <expresion_logica>

Expresiones y funciones
    <expresion>
    <lista_expresiones>
    <expresiones>
    <llamada_funcion>

Estructuras de control
    <if>
    <demas_if>
    <fin_if>
    <elif>
    <cadena_elif>
    <else>
    <while>
    <for>
    <estructura_control>

Sentencias y bloques
    <instruccion>
    <sentencia_simple>
    <lista_instrucciones>
    <bloque>
    <break>
    <return>

Parametros y funciones
    <parametro>
    <lista_parametros>
    <parametros>
    <funcion>
    <lista_funciones>
    <principal>
    <tipo_funcion>



------------------- Producciones -------------------
Caracteres y texto
    <letra> ::= [a-zA-Z]
    <digito> ::= [0-9]
    <digito_no_cero> ::= [1-9]
    <cero> ::= 0
    <lista_digitos> ::= <digito> | <digito> <lista_digitos>
    <simbolo> ::= "\@" | "\#" | "\$" | "\%" | "\^" | "\&" | "\*" | "\(" | "\)" | "\-" | "\_" | "\=" | "\+" | "\[" | "\]" | "\{" | "\}" | "\;" | "\:" | "\'" | "\<" | "\>" | "\," | "\." | "\/" | "\?" | "\\" | "\`" | "\~" | "\!" | "\|"
    <espacio> ::= " "
    <caracter> ::= <letra> | <digito> | <simbolo> | <espacio>
    <texto> ::= <caracter> | <caracter> <texto>
    <comillaDoble> ::= "\""
    <comillaSimple> ::= "\'"
    <guionBajo> ::= "\_"

Tipos y valores
    <tipoInt> ::= "int"
    <tipoFloat> ::= "float"
    <tipoBool> ::= "bool"
    <tipoChar> ::= "char"
    <tipoString> ::= "string"
    <tipoVoid> ::= "void"
    <true> ::= "true"
    <false> ::= "false"
    <not> ::= "Σ"
    <palabraVal> ::= "val"
    <leer> ::= "read"
    <escribir> ::= "write"
    <vacio> ::= ε

Delimitadores y operadores
    <abrir_bloque> ::= "¿:"
    <cerrar_bloque> ::= ":?"
    <abrir_parentesis> ::= "є:"
    <cerrar_parentesis> ::= ":э"
    <abrir_corcheteCuadrados> ::= "ʃ:"
    <cerrar_corcheteCuadrados> ::= ":ʅ"
    <coma> ::= ","
    <fin_sentencia> ::= "»"
    <asignacion> ::= "Ͱ"
    <incremento> ::= "++"
    <decremento> ::= "--"
    <palabraBreak> ::= "break"
    <palabraReturn> ::= "return"
    <palabraPrint> ::= "print"
    <palabraPrincipal> ::= "principal"
    <operadorPotencia> ::= "pot"

Palabras y operadores
    <simboloSuma> ::= "+"
    <simboloResta> ::= "-"
    <simboloMultiplicacion> ::= "*"
    <simboloDivision> ::= "/"
    <simboloDivisionEntera> ::= "//"
    <simboloMenor> ::= "<"
    <simboloMayor> ::= ">"
    <simboloMenorIgual> ::= "<="
    <simboloMayorIgual> ::= ">="
    <simboloIgual> ::= "=="
    <simboloDiferente> ::= "!="
    <simboloAnd> ::= "λ"
    <simboloOr> ::= "θ"
    <palabraIf> ::= "if"
    <palabraElif> ::= "elif"
    <palabraElse> ::= "else"
    <palabraWhile> ::= "while"
    <palabraFor> ::= "for"
    <modulo> ::= "mod"

Literales
    <entero> ::= <digito> | <digito_no_cero> <lista_digitos>
    <lista_digitos_no_cero_final> ::= <digito_no_cero> | <digito> <lista_digitos_no_cero_final>
    <flotante> ::= <cero> "\." <cero> | <cero> "\." <lista_digitos_no_cero_final> | <digito_no_cero> <lista_digitos> "\." <lista_digitos_no_cero_final>
    <bool> ::= <true> | <false>
    <cadena_texto> ::= <comillaDoble> (<vacio> | <texto>) <comillaDoble>
    <caracter_literal> ::= <comillaSimple> <caracter> <comillaSimple>
    <valor_numerico> ::= <entero> | <flotante>
    <valor> ::= <valor_numerico> | <bool> | <cadena_texto> | <caracter_literal> | <identificador> | <acceso_arreglo> | <llamada_funcion>
    <tipo> ::= <tipoInt> | <tipoFloat> | <tipoBool> | <tipoChar> | <tipoString> 

Identificadores
    <identificador> ::= <letra> | <letra> <resto_id>
    <resto_id> ::= <letra> | <digito> | <letra> <resto_id> | <digito> <resto_id> | <guionBajo> <letra> | <guionBajo> <digito> | <guionBajo> <letra> <resto_id> | <guionBajo> <digito> <resto_id>

Variables
    <variable> ::= <identificador>
    <def_variable> ::= <palabraVal> <tipo> <identificador> (<fin_sentencia> | <asignacion> <expresion> <fin_sentencia>)
    <asignacion_variable> ::= <variable> <asignacion> <expresion> <fin_sentencia>
    <lista_globales> ::= <vacio> | <def_variable> <lista_globales> | <creacion_arreglo> <lista_globales>

Entrada y salida
    <lectura> ::= <leer> (<variable> | <acceso_arreglo>) <fin_sentencia>
    <escritura> ::= <escribir> <valor_escritura> <fin_sentencia>
    <impresion> ::= <palabraPrint> <abrir_parentesis> <lista_valores> <cerrar_parentesis> <fin_sentencia>
    <lista_valores> ::= <valor_escritura> | <valor_escritura> <coma> <lista_valores>
    <valor_escritura> ::= <entero>  | <flotante>  | <bool>  | <cadena_texto>  | <caracter_literal>  | <variable>  | <acceso_arreglo>
Arreglos
    <indice> ::= <entero>
    <arreglo> ::= <identificador>
    <acceso_arreglo> ::= <arreglo> <abrir_corcheteCuadrados> <indice> <cerrar_corcheteCuadrados> ("arr ʃ:2:ʅ")
    <declaracion_arreglo> ::= <creacion_arreglo>
    <creacion_arreglo> ::= <arreglo_con_tamano> ("val int arr ʃ:3:ʅ »")
    <creacion_arreglo> ::= <arreglo_con_tamano_valores> ("val int arr ʃ:2:ʅ Ͱ ¿:2,3:? »")
    <creacion_arreglo> ::= <arreglo_sin_tamano_valores> ("val int arr ʃ::ʅ Ͱ ¿:1,2,3:? »")
    <arreglo_con_tamano> ::= <palabraVal> <tipo_arreglo> <identificador> <abrir_corcheteCuadrados> <indice> <cerrar_corcheteCuadrados> <fin_sentencia>
    <arreglo_con_tamano_valores> ::= <palabraVal> <tipo_arreglo> <identificador> <abrir_corcheteCuadrados> <indice> <cerrar_corcheteCuadrados> <asignacion> <abrir_bloque> <lista_arreglo> <cerrar_bloque> <fin_sentencia>
    <arreglo_sin_tamano_valores> ::= <palabraVal> <tipo_arreglo> <identificador> <abrir_corcheteCuadrados> <cerrar_corcheteCuadrados> <asignacion> <abrir_bloque> <lista_arreglo> <cerrar_bloque> <fin_sentencia>
    <lista_arreglo> ::= <inicio_lista_arreglo>
    <inicio_lista_arreglo> ::= <expresion_aritmetica> <continuacion_lista_arreglo>
    <continuacion_lista_arreglo> ::= <coma> <expresion_aritmetica> <continuacion_lista_arreglo> | <vacio>
    <modificacion_arreglo> ::= <acceso_arreglo> <asignacion> <expresion> <fin_sentencia> ("arr ʃ:1:ʅ Ͱ 8 »")
    <tipo_arreglo> ::= <tipoInt>
    <tipo_arreglo> ::= <tipoFloat>

Operaciones aritmeticas
    <operador_suma> ::= <simboloSuma> | <simboloResta>
    <operador_multiplicacion> ::= <simboloMultiplicacion> | <simboloDivision> | <simboloDivisionEntera> | <modulo>
    <expresion_aritmetica> ::= <expresion_suma>
    <expresion_suma> ::= <expresion_suma> <operador_suma> <expresion_multiplicacion> | <expresion_multiplicacion>
    <expresion_multiplicacion> ::= <expresion_multiplicacion> <operador_multiplicacion> <expresion_unaria> | <expresion_unaria>
    <expresion_unaria> ::= <simboloResta> <valor_numerico>| <expresion_potencia>
    <expresion_potencia> ::= <valor_aritmetico>    | <valor_aritmetico> <operadorPotencia> <exponente>
    <exponente> ::= <entero>   | <abrir_parentesis> <expresion_potencia> <cerrar_parentesis>
    <valor_aritmetico> ::= <valor_numerico> | <identificador> | <acceso_arreglo>  | <llamada_funcion> | <abrir_parentesis> <expresion_aritmetica> <cerrar_parentesis>
    <operacion_incremento> ::= <variable> <incremento>| <variable> <decremento>

Operaciones relacionales
    <operadorRelacional> ::= <simboloMenor> | <simboloMayor> | <simboloMenorIgual> | <simboloMayorIgual> | <simboloIgual> | <simboloDiferente>
    <operando_relacional> ::= <expresion_aritmetica> | <valor>
    <operacion_relacional> ::= <operando_relacional> <operadorRelacional> <operando_relacional>

Expresiones logicas
    <condicion_basica> ::= <abrir_parentesis> <operacion_relacional> <cerrar_parentesis> | <abrir_parentesis> <bool> <cerrar_parentesis> | <abrir_parentesis> <llamada_funcion> <cerrar_parentesis> | <abrir_parentesis> <identificador> <cerrar_parentesis> | <abrir_parentesis> <acceso_arreglo> <cerrar_parentesis> ("є: edad > 18 :э")
    <condiciones_and> ::= <condicion_basica> <simboloAnd> <condicion_basica> 
    <condiciones_or> ::= <condicion_basica> <simboloOr> <condicion_basica>
    <condiciones_logicas> ::= <abrir_parentesis> (<condiciones_and> | <condiciones_or>) <cerrar_parentesis> 
    <negacion> ::= <not> (<condicion_basica> | <condiciones_logicas>)
    <expresion_logica> ::= <condiciones_and> | <condiciones_or> | <negacion>

Expresiones y funciones
    <expresion> ::= <expresion_aritmetica> | <operacion_relacional> | <expresion_logica> | <valor>
    <lista_expresiones> ::= <vacio> | <expresiones>
    <expresiones> ::= <expresion> | <expresion> <coma> <expresiones>
    <llamada_funcion> ::= <identificador> <abrir_parentesis> <lista_expresiones> <cerrar_parentesis>

Estructuras de control
    <if> ::= <palabraIf> <abrir_parentesis> <expresion> <cerrar_parentesis> <abrir_bloque> <bloque> <cerrar_bloque> <demas_if>
    <demas_if> ::= <cadena_elif> <fin_if>   | <fin_if>
    <fin_if> ::= <else> | <vacio>
    <elif> ::= <palabraElif> <abrir_parentesis> <expresion> <cerrar_parentesis> <abrir_bloque> <bloque> <cerrar_bloque>
    <cadena_elif> ::= <elif>  | <elif> <cadena_elif>
    <else> ::= <palabraElse> <abrir_bloque> <bloque> <cerrar_bloque>

    <while> ::= <palabraWhile> <abrir_parentesis> <expresion> <cerrar_parentesis> <abrir_bloque> <bloque> <cerrar_bloque>
    <for> ::= <palabraFor> <abrir_parentesis>  <inicio_for>  <fin_sentencia>  <condicion_for>  <fin_sentencia>  <incremento_for>  <cerrar_parentesis>  <abrir_bloque>  <bloque>  <cerrar_bloque>
    <inicio_for> ::= <vacio>   | <variable> <asignacion> <expresion>
    <condicion_for> ::= <vacio> | <expresion>
    <incremento_for> ::= <vacio>  | <operacion_incremento> 
    <estructura_control> ::= <if> | <while> | <for>

Sentencias y bloques
    <break> ::= <palabraBreak>
    <return> ::= <palabraReturn> <fin_sentencia> | <palabraReturn> <expresion> <fin_sentencia>
    <instruccion> ::= <sentencia_simple> | <estructura_control>
    <sentencia_simple> ::= <asignacion_variable> | <def_variable>  | <creacion_arreglo>  | <modificacion_arreglo>  | <lectura>   | <escritura>  | <impresion>  | <operacion_incremento> <fin_sentencia>  | <llamada_funcion> <fin_sentencia> | <break> <fin_sentencia> | <return>
    <lista_instrucciones> ::= <instruccion> | <instruccion> <lista_instrucciones>
    <bloque> ::= <vacio> | <lista_instrucciones>

Parametros y funciones
    <tipo_funcion> ::= <tipo> | <tipoVoid>
    <parametro> ::= <tipo> <identificador>
    <lista_parametros> ::= <vacio> | <parametros>
    <parametros> ::= <parametro> | <parametro> <coma> <parametros>
    <funcion> ::= <tipo_funcion> <identificador> <abrir_parentesis> <lista_parametros> <cerrar_parentesis> <abrir_bloque> <bloque> <cerrar_bloque>
    <lista_funciones> ::= <vacio> | <funcion> <lista_funciones>
    <principal> ::= <tipoVoid> <palabraPrincipal> <abrir_parentesis> <cerrar_parentesis> <abrir_bloque> <bloque> <cerrar_bloque>
    <programa> ::= <lista_globales> <lista_funciones> <principal>