// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: Lexer.flex


@SuppressWarnings("fallthrough")
public class Lexer {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int COMENTARIO_MULTILINEA = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1, 1
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\1\u0200\1\u0300\1\u0400\33\u0100\1\u0500\267\u0100"+
    "\10\u0600\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\3\1\2\22\0\1\1\1\4"+
    "\1\5\4\6\1\7\2\6\1\10\1\11\1\12\1\13"+
    "\1\14\1\15\1\16\11\17\1\20\1\6\1\21\1\22"+
    "\1\23\1\24\1\6\4\25\1\26\25\25\4\6\1\27"+
    "\1\6\1\30\1\31\1\32\1\33\1\34\1\35\1\36"+
    "\1\37\1\40\1\25\1\41\1\42\1\43\1\44\1\45"+
    "\1\46\1\25\1\47\1\50\1\51\1\52\1\53\1\54"+
    "\3\25\1\6\1\55\2\6\6\0\1\3\33\0\1\56"+
    "\31\0\1\57\3\0\1\60\u01c3\0\1\61\1\0\1\62"+
    "\352\0\1\63\62\0\1\64\24\0\1\65\2\0\1\66"+
    "\221\0\1\67\6\0\1\70\323\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1792];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\3\1\1\3\1\4\1\5\1\6"+
    "\1\7\1\10\2\11\1\1\1\12\1\1\1\13\1\14"+
    "\1\1\15\14\1\2\1\15\1\16\2\1\1\17\1\20"+
    "\1\21\1\22\1\1\1\2\1\23\10\2\1\24\1\25"+
    "\2\0\1\26\1\27\1\30\1\0\2\31\2\32\1\33"+
    "\1\34\1\35\1\36\1\37\1\40\1\41\1\0\4\14"+
    "\1\42\1\43\4\14\1\44\13\14\1\45\1\46\1\47"+
    "\1\50\1\51\2\0\2\52\10\14\1\53\1\54\1\55"+
    "\1\56\5\14\1\57\3\14\1\60\1\61\1\62\1\14"+
    "\1\63\1\14\1\64\1\65\3\14\1\66\2\14\1\67"+
    "\1\70\2\14\1\71\1\72\1\73\1\74\3\14\1\75"+
    "\1\76\1\14\1\77\1\100\2\14\1\101";

  private static int [] zzUnpackAction() {
    int [] result = new int[159];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\71\0\162\0\253\0\344\0\u011d\0\u0156\0\162"+
    "\0\u018f\0\162\0\u01c8\0\162\0\u0201\0\u023a\0\u0273\0\u02ac"+
    "\0\u02e5\0\u031e\0\u0357\0\u0390\0\u03c9\0\u0402\0\u043b\0\u0474"+
    "\0\u04ad\0\u04e6\0\u051f\0\u0558\0\u0591\0\u05ca\0\u0603\0\u063c"+
    "\0\u0675\0\u06ae\0\u06e7\0\162\0\162\0\u0720\0\u0759\0\162"+
    "\0\162\0\162\0\162\0\u0792\0\162\0\344\0\u011d\0\u0156"+
    "\0\u02ac\0\u031e\0\u03c9\0\u0720\0\u0759\0\u0792\0\162\0\u011d"+
    "\0\u011d\0\u07cb\0\162\0\162\0\162\0\u0804\0\u083d\0\u0876"+
    "\0\u08af\0\u08e8\0\162\0\162\0\162\0\162\0\162\0\162"+
    "\0\u0921\0\u03c9\0\u095a\0\u0993\0\u09cc\0\u0a05\0\u0390\0\u0390"+
    "\0\u0a3e\0\u0a77\0\u0ab0\0\u0ae9\0\u0390\0\u0b22\0\u0b5b\0\u0b94"+
    "\0\u0bcd\0\u0c06\0\u0c3f\0\u0c78\0\u0cb1\0\u0cea\0\u0d23\0\u0d5c"+
    "\0\162\0\162\0\162\0\162\0\u0d95\0\u0dce\0\u083d\0\u08af"+
    "\0\u0e07\0\u0e40\0\u0e79\0\u0eb2\0\u0eeb\0\u0f24\0\u0f5d\0\u0f96"+
    "\0\u0fcf\0\u0390\0\u0390\0\u0390\0\u0390\0\u1008\0\u1041\0\u107a"+
    "\0\u10b3\0\u10ec\0\u0390\0\u1125\0\u115e\0\u1197\0\u0d95\0\u0dce"+
    "\0\u0390\0\u11d0\0\u0390\0\u1209\0\u0390\0\u0390\0\u1242\0\u127b"+
    "\0\u12b4\0\u0390\0\u12ed\0\u1326\0\u0390\0\u0390\0\u135f\0\u1398"+
    "\0\u0390\0\u0390\0\u0390\0\u0390\0\u13d1\0\u140a\0\u1443\0\u0390"+
    "\0\u0390\0\u147c\0\u0390\0\u0390\0\u14b5\0\u14ee\0\u0390";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[159];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\2\4\1\0\1\5\1\6\1\3\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\3\2\24\1\25\1\24\1\26"+
    "\1\27\1\30\1\31\1\32\2\24\1\33\2\24\1\34"+
    "\2\24\1\35\1\36\1\37\1\40\1\24\1\41\1\42"+
    "\1\43\1\44\1\45\1\46\1\47\1\3\1\50\1\51"+
    "\1\52\1\53\1\3\1\54\1\55\2\4\1\0\1\56"+
    "\1\57\1\55\1\60\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\61\1\21\1\62\1\23\1\55"+
    "\2\24\1\63\1\24\1\26\1\27\1\30\1\31\1\32"+
    "\2\24\1\33\2\24\1\34\2\24\1\35\1\36\1\37"+
    "\1\40\1\24\1\41\1\42\1\43\1\44\1\45\1\64"+
    "\1\65\1\55\1\50\1\51\1\52\1\53\1\55\1\66"+
    "\72\0\2\4\110\0\1\67\53\0\1\70\47\71\21\0"+
    "\50\72\25\0\1\73\72\0\1\74\72\0\1\75\67\0"+
    "\1\76\1\0\1\77\1\100\5\0\1\101\1\102\1\0"+
    "\4\101\1\102\20\101\30\0\1\76\1\0\2\17\5\0"+
    "\1\101\1\102\1\0\4\101\1\102\20\101\40\0\1\103"+
    "\35\0\1\104\4\0\1\105\23\0\1\106\70\0\1\107"+
    "\70\0\1\110\64\0\2\24\5\0\30\24\41\0\2\111"+
    "\1\112\25\111\32\0\2\24\5\0\20\24\1\113\1\24"+
    "\1\114\5\24\32\0\2\24\5\0\12\24\1\115\15\24"+
    "\32\0\2\24\5\0\7\24\1\116\1\24\1\117\3\24"+
    "\1\120\12\24\32\0\2\24\5\0\15\24\1\121\12\24"+
    "\32\0\2\24\5\0\3\24\1\122\11\24\1\123\2\24"+
    "\1\124\7\24\32\0\2\24\5\0\10\24\1\125\6\24"+
    "\1\126\10\24\32\0\2\24\5\0\20\24\1\127\7\24"+
    "\32\0\2\24\5\0\20\24\1\130\1\24\1\131\5\24"+
    "\32\0\2\24\5\0\7\24\1\132\20\24\32\0\2\24"+
    "\5\0\24\24\1\133\3\24\32\0\2\24\5\0\22\24"+
    "\1\134\5\24\32\0\2\24\5\0\3\24\1\135\14\24"+
    "\1\136\7\24\32\0\2\24\5\0\12\24\1\137\7\24"+
    "\1\140\5\24\14\0\2\43\1\0\66\43\20\0\1\141"+
    "\70\0\1\142\70\0\1\143\57\0\1\144\77\0\2\145"+
    "\65\0\1\146\1\0\2\147\5\0\2\101\1\0\25\101"+
    "\30\0\1\146\1\0\2\100\5\0\2\101\1\0\25\101"+
    "\32\0\2\101\5\0\30\101\32\0\1\150\1\151\5\0"+
    "\30\101\32\0\2\111\5\0\30\111\32\0\2\24\5\0"+
    "\20\24\1\152\7\24\32\0\2\24\5\0\7\24\1\153"+
    "\20\24\32\0\2\24\5\0\3\24\1\154\24\24\32\0"+
    "\2\24\5\0\10\24\1\155\17\24\32\0\2\24\5\0"+
    "\13\24\1\156\7\24\1\157\4\24\32\0\2\24\5\0"+
    "\15\24\1\160\12\24\32\0\2\24\5\0\20\24\1\161"+
    "\7\24\32\0\2\24\5\0\22\24\1\162\5\24\32\0"+
    "\2\24\5\0\24\24\1\163\3\24\32\0\2\24\5\0"+
    "\6\24\1\164\21\24\32\0\2\24\5\0\24\24\1\165"+
    "\3\24\32\0\2\24\5\0\13\24\1\166\14\24\32\0"+
    "\2\24\5\0\3\24\1\167\20\24\1\170\3\24\32\0"+
    "\2\24\5\0\22\24\1\171\5\24\32\0\2\24\5\0"+
    "\25\24\1\172\2\24\32\0\2\24\5\0\15\24\1\173"+
    "\12\24\32\0\2\24\5\0\13\24\1\174\14\24\32\0"+
    "\2\24\5\0\13\24\1\175\14\24\32\0\2\24\5\0"+
    "\13\24\1\176\14\24\32\0\1\177\1\145\67\0\2\200"+
    "\67\0\2\151\5\0\30\101\32\0\2\24\5\0\15\24"+
    "\1\201\12\24\32\0\2\24\5\0\3\24\1\202\24\24"+
    "\32\0\2\24\5\0\22\24\1\203\5\24\32\0\2\24"+
    "\5\0\25\24\1\204\2\24\32\0\2\24\5\0\10\24"+
    "\1\205\17\24\32\0\2\24\5\0\7\24\1\206\20\24"+
    "\32\0\2\24\5\0\23\24\1\207\4\24\32\0\2\24"+
    "\5\0\3\24\1\210\24\24\32\0\2\24\5\0\17\24"+
    "\1\211\10\24\32\0\2\24\5\0\6\24\1\212\21\24"+
    "\32\0\2\24\5\0\25\24\1\213\2\24\32\0\2\24"+
    "\5\0\13\24\1\214\14\24\32\0\2\24\5\0\7\24"+
    "\1\215\20\24\32\0\2\24\5\0\6\24\1\216\21\24"+
    "\32\0\2\24\5\0\15\24\1\217\12\24\32\0\2\24"+
    "\5\0\24\24\1\220\3\24\32\0\2\24\5\0\14\24"+
    "\1\221\13\24\32\0\2\24\5\0\17\24\1\222\10\24"+
    "\32\0\2\24\5\0\7\24\1\223\20\24\32\0\2\24"+
    "\5\0\24\24\1\224\3\24\32\0\2\24\5\0\5\24"+
    "\1\225\22\24\32\0\2\24\5\0\22\24\1\226\5\24"+
    "\32\0\2\24\5\0\17\24\1\227\10\24\32\0\2\24"+
    "\5\0\7\24\1\230\20\24\32\0\2\24\5\0\7\24"+
    "\1\231\20\24\32\0\2\24\5\0\13\24\1\232\14\24"+
    "\32\0\2\24\5\0\17\24\1\233\10\24\32\0\2\24"+
    "\5\0\11\24\1\234\16\24\32\0\2\24\5\0\21\24"+
    "\1\235\6\24\32\0\2\24\5\0\3\24\1\236\24\24"+
    "\32\0\2\24\5\0\15\24\1\237\12\24\14\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[5415];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\4\1\1\11\1\1\1\11\1\1\1\11"+
    "\27\1\2\11\2\1\4\11\1\1\1\11\11\1\1\11"+
    "\1\1\2\0\3\11\1\0\4\1\6\11\1\1\1\0"+
    "\26\1\4\11\1\1\2\0\70\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[159];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public java_cup.runtime.Symbol yylex() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { System.out.println(
        "Error léxico en la línea " + (yyline + 1) + 
        ", columna " + (yycolumn + 1) + 
        ": carácter no reconocido '" + yytext() + "'"
    );
            }
          // fall through
          case 66: break;
          case 2:
            { 
            }
          // fall through
          case 67: break;
          case 3:
            { return new java_cup.runtime.Symbol(sym.MULTIPLY);
            }
          // fall through
          case 68: break;
          case 4:
            { return new java_cup.runtime.Symbol(sym.PLUS);
            }
          // fall through
          case 69: break;
          case 5:
            { return new java_cup.runtime.Symbol(sym.COMA);
            }
          // fall through
          case 70: break;
          case 6:
            { return new java_cup.runtime.Symbol(sym.MINUS);
            }
          // fall through
          case 71: break;
          case 7:
            { return new java_cup.runtime.Symbol(sym.DOT);
            }
          // fall through
          case 72: break;
          case 8:
            { return new java_cup.runtime.Symbol(sym.FLOATDIV);
            }
          // fall through
          case 73: break;
          case 9:
            { return new java_cup.runtime.Symbol(sym.LITERAL_INT, yytext());
            }
          // fall through
          case 74: break;
          case 10:
            { return new java_cup.runtime.Symbol(sym.LT);
            }
          // fall through
          case 75: break;
          case 11:
            { return new java_cup.runtime.Symbol(sym.GT);
            }
          // fall through
          case 76: break;
          case 12:
            { return new java_cup.runtime.Symbol(sym.ID, yytext());
            }
          // fall through
          case 77: break;
          case 13:
            { yybegin(COMENTARIO_MULTILINEA);
            }
          // fall through
          case 78: break;
          case 14:
            { return new java_cup.runtime.Symbol(sym.TERMINATOR);
            }
          // fall through
          case 79: break;
          case 15:
            { return new java_cup.runtime.Symbol(sym.ASIGN);
            }
          // fall through
          case 80: break;
          case 16:
            { return new java_cup.runtime.Symbol(sym.NOT);
            }
          // fall through
          case 81: break;
          case 17:
            { return new java_cup.runtime.Symbol(sym.OR);
            }
          // fall through
          case 82: break;
          case 18:
            { return new java_cup.runtime.Symbol(sym.AND);
            }
          // fall through
          case 83: break;
          case 19:
            { yybegin(YYINITIAL);
            }
          // fall through
          case 84: break;
          case 20:
            { return new java_cup.runtime.Symbol(sym.NEQ);
            }
          // fall through
          case 85: break;
          case 21:
            { return new java_cup.runtime.Symbol(sym.LITERAL_STRING, yytext());
            }
          // fall through
          case 86: break;
          case 22:
            { return new java_cup.runtime.Symbol(sym.INCREMENT);
            }
          // fall through
          case 87: break;
          case 23:
            { return new java_cup.runtime.Symbol(sym.DECREMENT);
            }
          // fall through
          case 88: break;
          case 24:
            { return new java_cup.runtime.Symbol(sym.ENTIREDIV);
            }
          // fall through
          case 89: break;
          case 25:
            { //0031231
    System.out.println(
        "Error léxico en línea " + (yyline + 1) +
        ", columna " + (yycolumn + 1) +
        ": entero inválido '" + yytext() + "'"
    );
            }
          // fall through
          case 90: break;
          case 26:
            { //1x
    System.out.println(
        "Error léxico en línea " + (yyline + 1) +
        ", columna " + (yycolumn + 1) +
        ": identificador inválido '" + yytext() + "'"
    );
            }
          // fall through
          case 91: break;
          case 27:
            { return new java_cup.runtime.Symbol(sym.CLBLOCK);
            }
          // fall through
          case 92: break;
          case 28:
            { return new java_cup.runtime.Symbol(sym.CLBRACKET);
            }
          // fall through
          case 93: break;
          case 29:
            { return new java_cup.runtime.Symbol(sym.PARENCL);
            }
          // fall through
          case 94: break;
          case 30:
            { return new java_cup.runtime.Symbol(sym.LTE);
            }
          // fall through
          case 95: break;
          case 31:
            { return new java_cup.runtime.Symbol(sym.EQUAL);
            }
          // fall through
          case 96: break;
          case 32:
            { return new java_cup.runtime.Symbol(sym.GTE);
            }
          // fall through
          case 97: break;
          case 33:
            { //_counter
    System.out.println(
        "Error léxico en línea " + (yyline + 1) +
        ", columna " + (yycolumn + 1) +
        ": identificador inválido '" + yytext() + "'"
    );
            }
          // fall through
          case 98: break;
          case 34:
            { return new java_cup.runtime.Symbol(sym.GLOBAL);
            }
          // fall through
          case 99: break;
          case 35:
            { return new java_cup.runtime.Symbol(sym.LOCAL);
            }
          // fall through
          case 100: break;
          case 36:
            { return new java_cup.runtime.Symbol(sym.IF);
            }
          // fall through
          case 101: break;
          case 37:
            { return new java_cup.runtime.Symbol(sym.OPBLOCK);
            }
          // fall through
          case 102: break;
          case 38:
            { return new java_cup.runtime.Symbol(sym.OPBRACKET);
            }
          // fall through
          case 103: break;
          case 39:
            { return new java_cup.runtime.Symbol(sym.PARENOP);
            }
          // fall through
          case 104: break;
          case 40:
            { return new java_cup.runtime.Symbol(sym.LITERAL_CHAR, yytext());
            }
          // fall through
          case 105: break;
          case 41:
            { return new java_cup.runtime.Symbol(sym.LITERAL_FLOAT, yytext());
            }
          // fall through
          case 106: break;
          case 42:
            { return new java_cup.runtime.Symbol(sym.LITERAL_EXP, yytext());
            }
          // fall through
          case 107: break;
          case 43:
            { return new java_cup.runtime.Symbol(sym.FOR);
            }
          // fall through
          case 108: break;
          case 44:
            { return new java_cup.runtime.Symbol(sym.INT);
            }
          // fall through
          case 109: break;
          case 45:
            { return new java_cup.runtime.Symbol(sym.MOD);
            }
          // fall through
          case 110: break;
          case 46:
            { return new java_cup.runtime.Symbol(sym.POT);
            }
          // fall through
          case 111: break;
          case 47:
            { return new java_cup.runtime.Symbol(sym.VAL);
            }
          // fall through
          case 112: break;
          case 48:
            { //131.8940 o 0.8090
    System.out.println(
        "Error léxico en línea " + (yyline + 1) +
        ", columna " + (yycolumn + 1) +
        ": literal float inválido '" + yytext() + "'"
    );
            }
          // fall through
          case 113: break;
          case 49:
            { //05.1
    System.out.println(
        "Error léxico en línea " + (yyline + 1) +
        ", columna " + (yycolumn + 1) +
        ": literal float inválido '" + yytext() + "'"
    );
            }
          // fall through
          case 114: break;
          case 50:
            { return new java_cup.runtime.Symbol(sym.BOOL);
            }
          // fall through
          case 115: break;
          case 51:
            { return new java_cup.runtime.Symbol(sym.CHAR);
            }
          // fall through
          case 116: break;
          case 52:
            { return new java_cup.runtime.Symbol(sym.ELIF);
            }
          // fall through
          case 117: break;
          case 53:
            { return new java_cup.runtime.Symbol(sym.ELSE);
            }
          // fall through
          case 118: break;
          case 54:
            { return new java_cup.runtime.Symbol(sym.READ);
            }
          // fall through
          case 119: break;
          case 55:
            { return new java_cup.runtime.Symbol(sym.TRUE);
            }
          // fall through
          case 120: break;
          case 56:
            { return new java_cup.runtime.Symbol(sym.VOID);
            }
          // fall through
          case 121: break;
          case 57:
            { return new java_cup.runtime.Symbol(sym.BREAK);
            }
          // fall through
          case 122: break;
          case 58:
            { return new java_cup.runtime.Symbol(sym.DEFUN);
            }
          // fall through
          case 123: break;
          case 59:
            { return new java_cup.runtime.Symbol(sym.FALSE);
            }
          // fall through
          case 124: break;
          case 60:
            { return new java_cup.runtime.Symbol(sym.FLOAT);
            }
          // fall through
          case 125: break;
          case 61:
            { return new java_cup.runtime.Symbol(sym.WHILE);
            }
          // fall through
          case 126: break;
          case 62:
            { return new java_cup.runtime.Symbol(sym.WRITE);
            }
          // fall through
          case 127: break;
          case 63:
            { return new java_cup.runtime.Symbol(sym.RETURN);
            }
          // fall through
          case 128: break;
          case 64:
            { return new java_cup.runtime.Symbol(sym.STRING);
            }
          // fall through
          case 129: break;
          case 65:
            { return new java_cup.runtime.Symbol(sym.PRINCIPAL);
            }
          // fall through
          case 130: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
