// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: Lexer.flex


@SuppressWarnings("fallthrough")
public class Lexer {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int COMENTARIO_MULTILINEA = 2;
  public static final int STRING_INCOMPLETO = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1,  1,  2, 2
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\1\u0200\1\u0300\1\u0400\33\u0100\1\u0500\267\u0100"+
    "\10\u0600\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\3\1\2\22\0\1\1\1\4"+
    "\1\5\4\6\1\7\2\6\1\10\1\11\1\12\1\13"+
    "\1\14\1\15\1\16\11\17\1\20\1\6\1\21\1\22"+
    "\1\23\1\24\1\6\4\25\1\26\25\25\4\6\1\27"+
    "\1\6\1\30\1\31\1\32\1\33\1\34\1\35\1\36"+
    "\1\37\1\40\1\25\1\41\1\42\1\43\1\44\1\45"+
    "\1\46\1\25\1\47\1\50\1\51\1\52\1\53\1\54"+
    "\3\25\1\6\1\55\2\6\6\0\1\3\33\0\1\56"+
    "\31\0\1\57\3\0\1\60\u01c3\0\1\61\1\0\1\62"+
    "\352\0\1\63\62\0\1\64\24\0\1\65\2\0\1\66"+
    "\221\0\1\67\6\0\1\70\323\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1792];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\1\1\1\2\1\1\1\3\1\4\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\2\13\1\1\1\14\1\1"+
    "\1\15\1\16\1\17\1\1\3\16\1\17\11\16\1\2"+
    "\1\20\1\21\2\1\1\22\1\23\1\24\1\25\1\1"+
    "\1\2\1\26\6\2\2\27\1\30\1\4\2\27\1\17"+
    "\2\27\1\31\1\32\1\0\1\4\1\33\1\34\1\35"+
    "\1\36\1\0\2\37\1\40\2\17\1\41\1\42\1\43"+
    "\1\44\1\45\1\46\2\17\1\0\4\16\1\47\1\50"+
    "\4\16\1\51\13\16\1\52\1\53\1\54\1\4\1\33"+
    "\1\27\2\37\1\40\4\17\1\0\1\33\1\55\2\0"+
    "\3\17\2\56\10\16\1\57\1\60\1\61\1\62\5\16"+
    "\1\63\3\16\1\27\1\33\3\27\3\17\2\56\1\64"+
    "\1\65\1\0\1\65\1\0\1\66\1\16\1\67\1\16"+
    "\1\70\1\71\3\16\1\72\2\16\1\73\1\74\2\16"+
    "\1\64\1\65\1\27\1\65\1\27\3\17\1\75\1\76"+
    "\1\77\1\100\3\16\1\101\1\102\3\17\1\0\1\16"+
    "\1\103\1\104\1\27\2\16\1\105";

  private static int [] zzUnpackAction() {
    int [] result = new int[211];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\71\0\162\0\253\0\344\0\u011d\0\u0156\0\u018f"+
    "\0\253\0\u01c8\0\253\0\u0201\0\253\0\u023a\0\u0273\0\u02ac"+
    "\0\u02e5\0\u031e\0\u0357\0\u0390\0\u03c9\0\u0402\0\u043b\0\u0474"+
    "\0\u04ad\0\u04e6\0\u051f\0\u0558\0\u0591\0\u05ca\0\u0603\0\u063c"+
    "\0\u0675\0\u06ae\0\u06e7\0\u0720\0\u0759\0\253\0\253\0\u0792"+
    "\0\u07cb\0\253\0\253\0\253\0\253\0\u0804\0\253\0\u011d"+
    "\0\u02e5\0\u0357\0\u043b\0\u0792\0\u07cb\0\u0804\0\u083d\0\u0876"+
    "\0\344\0\u08af\0\u08e8\0\u0921\0\u095a\0\u0993\0\u09cc\0\253"+
    "\0\u0156\0\u0156\0\u0a05\0\u0a05\0\253\0\253\0\253\0\u0a3e"+
    "\0\u0a77\0\u0ab0\0\u0ae9\0\u0b22\0\u0b5b\0\253\0\253\0\253"+
    "\0\253\0\253\0\253\0\u03c9\0\u0b94\0\u043b\0\u0bcd\0\u0c06"+
    "\0\u0c3f\0\u0c78\0\u03c9\0\u03c9\0\u0cb1\0\u0cea\0\u0d23\0\u0d5c"+
    "\0\u03c9\0\u0d95\0\u0dce\0\u0e07\0\u0e40\0\u0e79\0\u0eb2\0\u0eeb"+
    "\0\u0f24\0\u0f5d\0\u0f96\0\u0fcf\0\253\0\253\0\253\0\u1008"+
    "\0\u1008\0\u1041\0\u107a\0\u10b3\0\u10ec\0\u1125\0\u115e\0\u083d"+
    "\0\u1197\0\u11d0\0\u11d0\0\u1209\0\u1242\0\u127b\0\u0ae9\0\u12b4"+
    "\0\u12ed\0\u12b4\0\u1326\0\u135f\0\u1398\0\u13d1\0\u140a\0\u1443"+
    "\0\u147c\0\u14b5\0\u14ee\0\u03c9\0\u03c9\0\u03c9\0\u03c9\0\u1527"+
    "\0\u1560\0\u1599\0\u15d2\0\u160b\0\u03c9\0\u1644\0\u167d\0\u16b6"+
    "\0\u16ef\0\u16ef\0\u1728\0\u1761\0\u179a\0\u10ec\0\u17d3\0\u180c"+
    "\0\u17d3\0\u1845\0\u11d0\0\u187e\0\u18b7\0\u1242\0\u18f0\0\u03c9"+
    "\0\u1929\0\u03c9\0\u1962\0\u03c9\0\u03c9\0\u199b\0\u19d4\0\u1a0d"+
    "\0\u03c9\0\u1a46\0\u1a7f\0\u03c9\0\u03c9\0\u1ab8\0\u1af1\0\u16ef"+
    "\0\u1b2a\0\u1b63\0\u1761\0\u1b9c\0\u1bd5\0\u1c0e\0\u1c47\0\u03c9"+
    "\0\u03c9\0\u03c9\0\u03c9\0\u1c80\0\u1cb9\0\u1cf2\0\u03c9\0\u03c9"+
    "\0\u1d2b\0\u1d64\0\u1d9d\0\u1c47\0\u1dd6\0\u03c9\0\u03c9\0\u1d9d"+
    "\0\u1e0f\0\u1e48\0\u03c9";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[211];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\2\5\1\0\1\6\1\7\1\4\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\1\24\1\4\1\25\1\26\1\27\1\25"+
    "\1\30\1\31\1\32\1\33\1\34\2\25\1\35\2\25"+
    "\1\36\2\25\1\37\1\40\1\41\1\42\1\25\1\43"+
    "\1\44\1\45\1\46\1\47\1\50\1\51\1\4\1\52"+
    "\1\53\1\54\1\55\1\4\1\56\1\57\2\5\1\0"+
    "\1\60\1\7\1\57\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\61\1\22\1\62\1\24"+
    "\1\57\1\25\1\26\1\63\1\25\1\30\1\31\1\32"+
    "\1\33\1\34\2\25\1\35\2\25\1\36\2\25\1\37"+
    "\1\40\1\41\1\42\1\25\1\43\1\44\1\45\1\46"+
    "\1\47\1\64\1\65\1\57\1\52\1\53\1\54\1\55"+
    "\1\57\1\66\1\67\1\70\1\71\2\67\1\7\1\67"+
    "\1\72\6\67\1\73\1\74\6\67\1\75\1\76\4\67"+
    "\1\75\20\67\1\77\13\67\72\0\2\5\110\0\1\100"+
    "\53\0\1\101\47\102\21\0\2\103\1\104\45\103\25\0"+
    "\1\105\72\0\1\106\72\0\1\107\67\0\1\110\1\0"+
    "\1\111\1\112\5\0\1\113\1\114\1\0\4\113\1\114"+
    "\20\113\30\0\1\110\1\0\2\20\5\0\1\113\1\115"+
    "\1\0\4\113\1\115\20\113\40\0\1\116\35\0\1\117"+
    "\4\0\1\120\23\0\1\121\70\0\1\122\70\0\1\123"+
    "\64\0\2\25\5\0\30\25\32\0\1\124\1\125\5\0"+
    "\30\25\41\0\2\113\1\126\25\113\32\0\2\25\5\0"+
    "\20\25\1\127\1\25\1\130\5\25\32\0\2\25\5\0"+
    "\12\25\1\131\15\25\32\0\2\25\5\0\7\25\1\132"+
    "\1\25\1\133\3\25\1\134\12\25\32\0\1\124\1\125"+
    "\5\0\15\25\1\135\12\25\32\0\2\25\5\0\3\25"+
    "\1\136\11\25\1\137\2\25\1\140\7\25\32\0\2\25"+
    "\5\0\10\25\1\141\6\25\1\142\10\25\32\0\2\25"+
    "\5\0\20\25\1\143\7\25\32\0\2\25\5\0\20\25"+
    "\1\144\1\25\1\145\5\25\32\0\2\25\5\0\7\25"+
    "\1\146\20\25\32\0\2\25\5\0\24\25\1\147\3\25"+
    "\32\0\2\25\5\0\22\25\1\150\5\25\32\0\2\25"+
    "\5\0\3\25\1\151\14\25\1\152\7\25\32\0\2\25"+
    "\5\0\12\25\1\153\7\25\1\154\5\25\14\0\2\45"+
    "\1\0\66\45\20\0\1\155\70\0\1\156\70\0\1\157"+
    "\50\0\2\67\1\0\2\67\1\0\64\67\1\70\1\5"+
    "\2\67\1\0\65\67\1\0\2\67\1\103\1\160\1\161"+
    "\45\160\16\67\1\0\2\67\1\0\6\67\1\162\1\67"+
    "\1\163\1\164\5\67\1\165\1\166\1\67\4\165\1\166"+
    "\20\165\16\67\1\0\2\67\1\0\6\67\1\162\1\67"+
    "\2\74\5\67\1\165\1\167\1\67\4\165\1\167\20\165"+
    "\16\67\1\0\2\67\1\0\10\67\1\170\1\171\53\67"+
    "\1\0\2\67\1\0\17\67\2\165\1\76\25\165\14\67"+
    "\2\77\1\0\2\77\1\45\63\77\5\0\2\172\1\173"+
    "\45\172\32\0\2\174\65\0\1\175\1\0\2\176\5\0"+
    "\1\113\1\177\1\0\4\113\1\177\20\113\30\0\1\175"+
    "\1\0\2\112\5\0\1\113\1\177\1\0\4\113\1\177"+
    "\20\113\32\0\2\113\5\0\30\113\32\0\1\200\1\201"+
    "\5\0\30\113\32\0\1\202\1\203\5\0\30\113\32\0"+
    "\2\125\5\0\30\25\32\0\2\25\5\0\20\25\1\204"+
    "\7\25\32\0\2\25\5\0\7\25\1\205\20\25\32\0"+
    "\2\25\5\0\3\25\1\206\24\25\32\0\2\25\5\0"+
    "\10\25\1\207\17\25\32\0\2\25\5\0\13\25\1\210"+
    "\7\25\1\211\4\25\32\0\2\25\5\0\15\25\1\212"+
    "\12\25\32\0\2\25\5\0\20\25\1\213\7\25\32\0"+
    "\2\25\5\0\22\25\1\214\5\25\32\0\2\25\5\0"+
    "\24\25\1\215\3\25\32\0\2\25\5\0\6\25\1\216"+
    "\21\25\32\0\2\25\5\0\24\25\1\217\3\25\32\0"+
    "\2\25\5\0\13\25\1\220\14\25\32\0\2\25\5\0"+
    "\3\25\1\221\20\25\1\222\3\25\32\0\2\25\5\0"+
    "\22\25\1\223\5\25\32\0\2\25\5\0\25\25\1\224"+
    "\2\25\32\0\2\25\5\0\15\25\1\225\12\25\32\0"+
    "\2\25\5\0\13\25\1\226\14\25\32\0\2\25\5\0"+
    "\13\25\1\227\14\25\32\0\2\25\5\0\13\25\1\230"+
    "\14\25\14\0\2\67\1\0\2\67\1\172\1\231\1\232"+
    "\45\231\16\67\1\0\2\67\1\0\10\67\2\233\53\67"+
    "\1\0\2\67\1\0\6\67\1\234\1\67\2\235\5\67"+
    "\1\165\1\236\1\67\4\165\1\236\20\165\16\67\1\0"+
    "\2\67\1\0\6\67\1\234\1\67\2\164\5\67\1\165"+
    "\1\236\1\67\4\165\1\236\20\165\16\67\1\0\2\67"+
    "\1\0\10\67\2\165\5\67\30\165\16\67\1\0\2\67"+
    "\1\0\10\67\1\237\1\240\5\67\30\165\16\67\1\0"+
    "\2\67\1\0\10\67\1\241\1\242\5\67\30\165\16\67"+
    "\1\0\2\67\1\0\10\67\2\171\51\67\5\0\2\172"+
    "\1\243\45\172\32\0\1\244\1\174\6\0\1\245\5\0"+
    "\1\245\52\0\2\246\65\0\1\175\1\0\2\176\5\0"+
    "\2\113\1\0\25\113\30\0\1\247\1\0\2\113\5\0"+
    "\30\113\30\0\1\247\1\0\2\201\5\0\30\113\30\0"+
    "\1\247\1\0\2\203\5\0\30\113\32\0\2\25\5\0"+
    "\15\25\1\250\12\25\32\0\2\25\5\0\3\25\1\251"+
    "\24\25\32\0\2\25\5\0\22\25\1\252\5\25\32\0"+
    "\2\25\5\0\25\25\1\253\2\25\32\0\2\25\5\0"+
    "\10\25\1\254\17\25\32\0\2\25\5\0\7\25\1\255"+
    "\20\25\32\0\2\25\5\0\23\25\1\256\4\25\32\0"+
    "\2\25\5\0\3\25\1\257\24\25\32\0\2\25\5\0"+
    "\17\25\1\260\10\25\32\0\2\25\5\0\6\25\1\261"+
    "\21\25\32\0\2\25\5\0\25\25\1\262\2\25\32\0"+
    "\2\25\5\0\13\25\1\263\14\25\32\0\2\25\5\0"+
    "\7\25\1\264\20\25\32\0\2\25\5\0\6\25\1\265"+
    "\21\25\32\0\2\25\5\0\15\25\1\266\12\25\32\0"+
    "\2\25\5\0\24\25\1\267\3\25\14\0\2\67\1\0"+
    "\2\67\1\172\1\231\1\270\45\231\16\67\1\0\2\67"+
    "\1\0\10\67\1\271\1\233\6\67\1\272\5\67\1\272"+
    "\36\67\1\0\2\67\1\0\10\67\2\273\53\67\1\0"+
    "\2\67\1\0\6\67\1\234\1\67\2\235\5\67\2\165"+
    "\1\67\25\165\16\67\1\0\2\67\1\0\6\67\1\274"+
    "\1\67\2\165\5\67\30\165\16\67\1\0\2\67\1\0"+
    "\6\67\1\274\1\67\2\240\5\67\30\165\16\67\1\0"+
    "\2\67\1\0\6\67\1\274\1\67\2\242\5\67\30\165"+
    "\14\67\16\0\1\244\1\174\67\0\1\275\1\276\67\0"+
    "\2\277\67\0\2\25\5\0\14\25\1\300\13\25\32\0"+
    "\2\25\5\0\17\25\1\301\10\25\32\0\2\25\5\0"+
    "\7\25\1\302\20\25\32\0\2\25\5\0\24\25\1\303"+
    "\3\25\32\0\2\25\5\0\5\25\1\304\22\25\32\0"+
    "\2\25\5\0\22\25\1\305\5\25\32\0\2\25\5\0"+
    "\17\25\1\306\10\25\32\0\2\25\5\0\7\25\1\307"+
    "\20\25\32\0\2\25\5\0\7\25\1\310\20\25\14\0"+
    "\2\67\1\0\2\67\1\0\10\67\1\271\1\233\53\67"+
    "\1\0\2\67\1\0\10\67\1\311\1\312\53\67\1\0"+
    "\2\67\1\0\10\67\2\313\51\67\14\0\1\247\70\0"+
    "\1\247\1\0\2\276\67\0\1\314\1\277\67\0\2\25"+
    "\5\0\13\25\1\315\14\25\32\0\2\25\5\0\17\25"+
    "\1\316\10\25\32\0\2\25\5\0\11\25\1\317\16\25"+
    "\14\0\2\67\1\0\2\67\1\0\6\67\1\274\56\67"+
    "\1\0\2\67\1\0\6\67\1\274\1\67\2\312\53\67"+
    "\1\0\2\67\1\0\10\67\1\320\1\313\51\67\16\0"+
    "\2\25\5\0\21\25\1\321\6\25\32\0\2\25\5\0"+
    "\3\25\1\322\24\25\32\0\2\25\5\0\15\25\1\323"+
    "\12\25\14\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[7809];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\1\11\4\1\1\11\1\1\1\11\1\1\1\11"+
    "\30\1\2\11\2\1\4\11\1\1\1\11\20\1\1\11"+
    "\1\1\1\0\2\1\3\11\1\0\5\1\6\11\2\1"+
    "\1\0\26\1\3\11\12\1\1\0\2\1\2\0\46\1"+
    "\1\0\1\1\1\0\44\1\1\0\7\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[211];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public java_cup.runtime.Symbol yylex() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            switch (zzLexicalState) {
            case STRING_INCOMPLETO: {
              System.out.println(
            "Error léxico en línea " + (yyline + 1) +
            ", columna " + (yycolumn + 1) +
            ": literal string incompleto"
        );
        return null;
            }  // fall though
            case 212: break;
            default:
        return null;
        }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { System.out.println(
        "Error léxico en la línea " + (yyline + 1) +
        ", columna " + (yycolumn + 1) +
        ": carácter no reconocido '" + yytext() + "'"
    );
            }
          // fall through
          case 70: break;
          case 2:
            { 
            }
          // fall through
          case 71: break;
          case 3:
            { yybegin(STRING_INCOMPLETO);
            }
          // fall through
          case 72: break;
          case 4:
            { System.out.println(
        "Error léxico en línea " + (yyline + 1) +
        ", columna " + (yycolumn + 1) +
        ": literal char incompleto '" + yytext() + "'"
    );
            }
          // fall through
          case 73: break;
          case 5:
            { return new java_cup.runtime.Symbol(sym.MULTIPLY);
            }
          // fall through
          case 74: break;
          case 6:
            { return new java_cup.runtime.Symbol(sym.PLUS);
            }
          // fall through
          case 75: break;
          case 7:
            { return new java_cup.runtime.Symbol(sym.COMA);
            }
          // fall through
          case 76: break;
          case 8:
            { return new java_cup.runtime.Symbol(sym.MINUS);
            }
          // fall through
          case 77: break;
          case 9:
            { return new java_cup.runtime.Symbol(sym.DOT);
            }
          // fall through
          case 78: break;
          case 10:
            { return new java_cup.runtime.Symbol(sym.FLOATDIV);
            }
          // fall through
          case 79: break;
          case 11:
            { return new java_cup.runtime.Symbol(sym.LITERAL_INT, yytext());
            }
          // fall through
          case 80: break;
          case 12:
            { return new java_cup.runtime.Symbol(sym.LT);
            }
          // fall through
          case 81: break;
          case 13:
            { return new java_cup.runtime.Symbol(sym.GT);
            }
          // fall through
          case 82: break;
          case 14:
            { return new java_cup.runtime.Symbol(sym.ID, yytext());
            }
          // fall through
          case 83: break;
          case 15:
            { System.out.println(
        "Error léxico en línea " + (yyline + 1) +
        ", columna " + (yycolumn + 1) +
        ": literal exp inválido '" + yytext() + "'"
    );
            }
          // fall through
          case 84: break;
          case 16:
            { yybegin(COMENTARIO_MULTILINEA);
            }
          // fall through
          case 85: break;
          case 17:
            { return new java_cup.runtime.Symbol(sym.TERMINATOR);
            }
          // fall through
          case 86: break;
          case 18:
            { return new java_cup.runtime.Symbol(sym.ASIGN);
            }
          // fall through
          case 87: break;
          case 19:
            { return new java_cup.runtime.Symbol(sym.NOT);
            }
          // fall through
          case 88: break;
          case 20:
            { return new java_cup.runtime.Symbol(sym.OR);
            }
          // fall through
          case 89: break;
          case 21:
            { return new java_cup.runtime.Symbol(sym.AND);
            }
          // fall through
          case 90: break;
          case 22:
            { yybegin(YYINITIAL);
            }
          // fall through
          case 91: break;
          case 23:
            { // Se continúa consumiendo el contenido para no detener la ejecución
            }
          // fall through
          case 92: break;
          case 24:
            { System.out.println(
            "Error léxico en línea " + (yyline + 1) +
            ", columna " + (yycolumn + 1) +
            ": literal string incompleto"
        );
        yybegin(YYINITIAL);
            }
          // fall through
          case 93: break;
          case 25:
            { return new java_cup.runtime.Symbol(sym.NEQ);
            }
          // fall through
          case 94: break;
          case 26:
            { return new java_cup.runtime.Symbol(sym.LITERAL_STRING, yytext());
            }
          // fall through
          case 95: break;
          case 27:
            { return new java_cup.runtime.Symbol(sym.LITERAL_CHAR, yytext());
            }
          // fall through
          case 96: break;
          case 28:
            { return new java_cup.runtime.Symbol(sym.INCREMENT);
            }
          // fall through
          case 97: break;
          case 29:
            { return new java_cup.runtime.Symbol(sym.DECREMENT);
            }
          // fall through
          case 98: break;
          case 30:
            { return new java_cup.runtime.Symbol(sym.ENTIREDIV);
            }
          // fall through
          case 99: break;
          case 31:
            { System.out.println(
        "Error léxico en línea " + (yyline + 1) +
        ", columna " + (yycolumn + 1) +
        ": entero inválido '" + yytext() + "'"
    );
            }
          // fall through
          case 100: break;
          case 32:
            { System.out.println(
        "Error léxico en línea " + (yyline + 1) +
        ", columna " + (yycolumn + 1) +
        ": identificador inválido '" + yytext() + "'"
    );
            }
          // fall through
          case 101: break;
          case 33:
            { return new java_cup.runtime.Symbol(sym.CLBLOCK);
            }
          // fall through
          case 102: break;
          case 34:
            { return new java_cup.runtime.Symbol(sym.CLBRACKET);
            }
          // fall through
          case 103: break;
          case 35:
            { return new java_cup.runtime.Symbol(sym.PARENCL);
            }
          // fall through
          case 104: break;
          case 36:
            { return new java_cup.runtime.Symbol(sym.LTE);
            }
          // fall through
          case 105: break;
          case 37:
            { return new java_cup.runtime.Symbol(sym.EQUAL);
            }
          // fall through
          case 106: break;
          case 38:
            { return new java_cup.runtime.Symbol(sym.GTE);
            }
          // fall through
          case 107: break;
          case 39:
            { return new java_cup.runtime.Symbol(sym.GLOBAL);
            }
          // fall through
          case 108: break;
          case 40:
            { return new java_cup.runtime.Symbol(sym.LOCAL);
            }
          // fall through
          case 109: break;
          case 41:
            { return new java_cup.runtime.Symbol(sym.IF);
            }
          // fall through
          case 110: break;
          case 42:
            { return new java_cup.runtime.Symbol(sym.OPBLOCK);
            }
          // fall through
          case 111: break;
          case 43:
            { return new java_cup.runtime.Symbol(sym.OPBRACKET);
            }
          // fall through
          case 112: break;
          case 44:
            { return new java_cup.runtime.Symbol(sym.PARENOP);
            }
          // fall through
          case 113: break;
          case 45:
            { return new java_cup.runtime.Symbol(sym.LITERAL_FLOAT, yytext());
            }
          // fall through
          case 114: break;
          case 46:
            { return new java_cup.runtime.Symbol(sym.LITERAL_EXP, yytext());
            }
          // fall through
          case 115: break;
          case 47:
            { return new java_cup.runtime.Symbol(sym.FOR);
            }
          // fall through
          case 116: break;
          case 48:
            { return new java_cup.runtime.Symbol(sym.INT);
            }
          // fall through
          case 117: break;
          case 49:
            { return new java_cup.runtime.Symbol(sym.MOD);
            }
          // fall through
          case 118: break;
          case 50:
            { return new java_cup.runtime.Symbol(sym.POT);
            }
          // fall through
          case 119: break;
          case 51:
            { return new java_cup.runtime.Symbol(sym.VAL);
            }
          // fall through
          case 120: break;
          case 52:
            { System.out.println(
        "Error léxico en línea " + (yyline + 1) +
        ", columna " + (yycolumn + 1) +
        ": literal char inválido '" + yytext() + "'"
    );
            }
          // fall through
          case 121: break;
          case 53:
            { System.out.println(
        "Error léxico en línea " + (yyline + 1) +
        ", columna " + (yycolumn + 1) +
        ": literal float inválido '" + yytext() + "'"
    );
            }
          // fall through
          case 122: break;
          case 54:
            { return new java_cup.runtime.Symbol(sym.BOOL);
            }
          // fall through
          case 123: break;
          case 55:
            { return new java_cup.runtime.Symbol(sym.CHAR);
            }
          // fall through
          case 124: break;
          case 56:
            { return new java_cup.runtime.Symbol(sym.ELIF);
            }
          // fall through
          case 125: break;
          case 57:
            { return new java_cup.runtime.Symbol(sym.ELSE);
            }
          // fall through
          case 126: break;
          case 58:
            { return new java_cup.runtime.Symbol(sym.READ);
            }
          // fall through
          case 127: break;
          case 59:
            { return new java_cup.runtime.Symbol(sym.TRUE);
            }
          // fall through
          case 128: break;
          case 60:
            { return new java_cup.runtime.Symbol(sym.VOID);
            }
          // fall through
          case 129: break;
          case 61:
            { return new java_cup.runtime.Symbol(sym.BREAK);
            }
          // fall through
          case 130: break;
          case 62:
            { return new java_cup.runtime.Symbol(sym.DEFUN);
            }
          // fall through
          case 131: break;
          case 63:
            { return new java_cup.runtime.Symbol(sym.FALSE);
            }
          // fall through
          case 132: break;
          case 64:
            { return new java_cup.runtime.Symbol(sym.FLOAT);
            }
          // fall through
          case 133: break;
          case 65:
            { return new java_cup.runtime.Symbol(sym.WHILE);
            }
          // fall through
          case 134: break;
          case 66:
            { return new java_cup.runtime.Symbol(sym.WRITE);
            }
          // fall through
          case 135: break;
          case 67:
            { return new java_cup.runtime.Symbol(sym.RETURN);
            }
          // fall through
          case 136: break;
          case 68:
            { return new java_cup.runtime.Symbol(sym.STRING);
            }
          // fall through
          case 137: break;
          case 69:
            { return new java_cup.runtime.Symbol(sym.PRINCIPAL);
            }
          // fall through
          case 138: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
