
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int OPBRACKET = 24;
  public static final int VAL = 29;
  public static final int LTE = 11;
  public static final int POT = 10;
  public static final int INCREMENT = 2;
  public static final int TERMINATOR = 26;
  public static final int CHAR = 34;
  public static final int INT = 31;
  public static final int FOR = 43;
  public static final int MINUS = 5;
  public static final int DECREMENT = 4;
  public static final int WRITE = 48;
  public static final int PRINCIPAL = 30;
  public static final int NOT = 19;
  public static final int AND = 17;
  public static final int LT = 15;
  public static final int OR = 18;
  public static final int BOOL = 33;
  public static final int PLUS = 3;
  public static final int MULTIPLY = 6;
  public static final int IF = 39;
  public static final int ID = 53;
  public static final int EOF = 0;
  public static final int RETURN = 44;
  public static final int EQUAL = 13;
  public static final int TRUE = 37;
  public static final int FLOATDIV = 8;
  public static final int error = 1;
  public static final int COMA = 28;
  public static final int LITERAL_CHAR = 52;
  public static final int MOD = 9;
  public static final int NEQ = 14;
  public static final int CLBRACKET = 25;
  public static final int BREAK = 45;
  public static final int VOID = 36;
  public static final int LITERAL_FLOAT = 50;
  public static final int GTE = 12;
  public static final int ENTIREDIV = 7;
  public static final int LITERAL_INT = 49;
  public static final int ELSE = 41;
  public static final int CLBLOCK = 21;
  public static final int READ = 47;
  public static final int LITERAL_STRING = 51;
  public static final int WHILE = 42;
  public static final int FLOAT = 32;
  public static final int OPBLOCK = 20;
  public static final int ASIGN = 27;
  public static final int STRING = 35;
  public static final int FALSE = 38;
  public static final int PARENCL = 23;
  public static final int GT = 16;
  public static final int PARENOP = 22;
  public static final int ELIF = 40;
  public static final int PRINT = 46;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INCREMENT",
  "PLUS",
  "DECREMENT",
  "MINUS",
  "MULTIPLY",
  "ENTIREDIV",
  "FLOATDIV",
  "MOD",
  "POT",
  "LTE",
  "GTE",
  "EQUAL",
  "NEQ",
  "LT",
  "GT",
  "AND",
  "OR",
  "NOT",
  "OPBLOCK",
  "CLBLOCK",
  "PARENOP",
  "PARENCL",
  "OPBRACKET",
  "CLBRACKET",
  "TERMINATOR",
  "ASIGN",
  "COMA",
  "VAL",
  "PRINCIPAL",
  "INT",
  "FLOAT",
  "BOOL",
  "CHAR",
  "STRING",
  "VOID",
  "TRUE",
  "FALSE",
  "IF",
  "ELIF",
  "ELSE",
  "WHILE",
  "FOR",
  "RETURN",
  "BREAK",
  "PRINT",
  "READ",
  "WRITE",
  "LITERAL_INT",
  "LITERAL_FLOAT",
  "LITERAL_STRING",
  "LITERAL_CHAR",
  "ID"
  };
}

